# Generated by Django 3.2.15 on 2022-10-17 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_contact_contact', serialize=False, to='cms.cmsplugin')),
                ('form_name', models.CharField(blank=True, help_text='Used to distinguish multiple contact forms on the same site.', max_length=60, verbose_name='Form name')),
                ('form_layout', models.CharField(choices=[('cmsplugin_contact.forms.ContactForm', 'default')], help_text='Choose the layout of contact form', max_length=255, verbose_name='Form Layout')),
                ('site_email', models.EmailField(max_length=254, verbose_name='Email recipient')),
                ('thanks', models.TextField(default='Thank you for your message.', help_text='Message displayed on successful submit', max_length=200, verbose_name='Thanks message')),
                ('submit_text', models.CharField(default='Submit', max_length=30, verbose_name='Submit button value')),
                ('spam_protection_method', models.SmallIntegerField(choices=[(0, 'Honeypot'), (1, 'Akismet'), (2, 'ReCAPTCHA')], default=0, verbose_name='Spam protection method')),
                ('akismet_api_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_public_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_private_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20, verbose_name='ReCAPTCHA theme')),
                ('recaptcha_size', models.CharField(choices=[('normal', 'Normal'), ('compact', 'Compact')], default='normal', max_length=20, verbose_name='ReCAPTCHA size')),
                ('redirect_url', models.URLField(blank=True, help_text='If it is set, the form redirect to url when the form is valid', verbose_name='URL Redirection')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
