# Generated by Django 4.2.6 on 2023-10-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsplugin_cmsplugin_ptr_imagepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
