# Generated by Django 4.2.6 on 2023-10-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_imagepost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_position',
        ),
    ]
