# Generated by Django 4.2.6 on 2023-10-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_post_image_remove_post_image_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, help_text="Как правило содержится в атрибуте 'src'                                         тега 'iframe' экспортируемого видео.", max_length=512, null=True, verbose_name='Ссылка на видео')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
            },
        ),
    ]
