# Generated by Django 4.2.6 on 2023-10-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_videopost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopost',
            old_name='video',
            new_name='video_url',
        ),
    ]
