# Generated by Django 4.1.12 on 2023-11-03 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PureCodePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('code', models.TextField(blank=True, help_text='Использовать js и css здесь возможно, но не рекомендуется.', null=True, verbose_name='HTML')),
                ('css', models.TextField(blank=True, null=True, verbose_name='CSS')),
                ('js', models.TextField(blank=True, help_text='Доступно использование jQuery, пример "$(document).ready(function () {                           alert("test");});"', null=True, verbose_name='JAVASCRIPT')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
